/* Copyright (C) 2020-2021 Patrick Ziegler
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

// auto generated by moc
#include "ui_dialog.h"

#include "worker.hpp"

#include <QDialog>

class QAbstractButton;
class QPushButton;

class MediaCopierDialog : public QDialog
{
    Q_OBJECT

public:
    explicit MediaCopierDialog(Worker *worker, QWidget *parent = nullptr);
    ~MediaCopierDialog();

private slots:
    // dialog related slots
    void onOpenInputDirClicked();
    void onOpenOutputDirClicked();
    void onDialogControlClicked(QAbstractButton *button);
    void onInputDirChanged(const QString& text);
    void onOutputDirChanged(const QString& text);
    void onBaseFormatChanged(const QString& text);
    void onOperationChanged(int index);

    // worker related slots
    void onAppendLog(QString message);
    void onSetProgress(int value);
    void onResetProgress(int value);
    void onOperationFinished();

private:
    QPushButton* m_btnOk = nullptr;
    QThread* m_thread = nullptr;
    Worker* m_worker = nullptr;
    Ui::MediaCopierDialog *ui = nullptr;
};
