/* Copyright (C) 2022 Patrick Ziegler
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

// auto generated by moc
#include "ui_dialog.h"

#include <QDialog>
#include <QStateMachine>

class Config;
class Worker;

class MediaCopierDialog : public QDialog
{
    Q_OBJECT

public:
    explicit MediaCopierDialog(Config* config, QWidget *parent=nullptr);
    ~MediaCopierDialog();

private:
    void initStateMachine();
    void syncConfig();

public Q_SLOTS:
    void aboutToQuit();

private Q_SLOTS:
    void onOpenInputDirClicked();
    void onOpenOutputDirClicked();
    void onInputDirChanged(const QString& text);
    void onOutputDirChanged(const QString& text);
    void onBaseFormatChanged(const QString& text);
    void onCommandChanged(int index);
    void startOperation();
    void cancelOperation();

Q_SIGNALS:
    void operationDone();

private:
    Ui::MediaCopierDialog* ui = nullptr;
    QStateMachine* fsm = nullptr;
    Config* m_config = nullptr;
    Worker* m_worker = nullptr;
};
