/* Copyright (C) 2022 Patrick Ziegler
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "dialog_kde.hpp"
#include "job.hpp"

#include <mediacopier/version.hpp>

#include <QApplication>
#include <QFinalState>
#include <QScreen>

#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>

// auto generated by moc
#include "ui_dialog_kde.h"

static constexpr const size_t DEFAULT_DIALOG_WIDTH = 700;
static constexpr const size_t DEFAULT_DIALOG_HEIGHT = 200;
static constexpr const unsigned int DEFAULT_WAIT_MS = 200;

KMediaCopierDialog::KMediaCopierDialog(QWidget *parent) :
    QDialog(parent), ui(new Ui::KMediaCopierDialog)
{
    ui->setupUi(this);
    this->setWindowTitle(mediacopier::MEDIACOPIER_PROJECT_NAME);
    this->resize(DEFAULT_DIALOG_WIDTH, DEFAULT_DIALOG_HEIGHT);
    move(screen()->geometry().center() - frameGeometry().center());
}

KMediaCopierDialog::~KMediaCopierDialog()
{
    delete ui;
}

void KMediaCopierDialog::init(std::shared_ptr<Config> config, QApplication& app)
{
    app.setDesktopFileName("org.kde.dolphin");

    this->config = std::move(config);
    ui->param->init(this->config);

    fsm = std::make_unique<QStateMachine>();

    auto s1 = new QState();         // waiting for input
    auto s2 = new QState();         // executing operation
    auto s3 = new QFinalState();    // closing dialog

    s1->addTransition(ui->dialogButtonBox, &QDialogButtonBox::accepted, s2);
    s1->addTransition(ui->dialogButtonBox, &QDialogButtonBox::rejected, s3);
    s2->addTransition(this, &KMediaCopierDialog::operationDone, s3);

    QObject::connect(s2, &QState::entered, this, &KMediaCopierDialog::hide);
    QObject::connect(s2, &QState::entered, this, &KMediaCopierDialog::startOperation);
    QObject::connect(fsm.get(), &QStateMachine::finished, this, &KMediaCopierDialog::close);

    fsm->addState(s1);
    fsm->addState(s2);
    fsm->addState(s3);
    fsm->setInitialState(s1);
    fsm->start();
}

void KMediaCopierDialog::startOperation()
{
    worker = std::make_shared<Worker>(*config);
    QObject::connect(worker.get(), &Worker::finished, this, &KMediaCopierDialog::operationDone);

    auto job = new KMediaCopierJob(worker, config->outputDir());
    tracker.registerJob(job); // tracker takes ownership of job

    if (spdlog::default_logger()->sinks().size() > 1) {
        spdlog::default_logger()->sinks().pop_back();
    }
    auto logfile = config->outputDir() / ".mediacopier-log";
    spdlog::default_logger()->sinks().push_back(
                std::make_shared<spdlog::sinks::basic_file_sink_mt>(logfile.string(), true));

    worker->start();
}
