/* Copyright (C) 2022 Patrick Ziegler
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "gui/dialog_slim.hpp"

#include <mediacopier/version.hpp>

#include <QApplication>
#include <QFinalState>
#include <QPushButton>
#include <QScreen>

#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>

// auto generated by moc
#include "ui_dialog_slim.h"

static constexpr const size_t DEFAULT_DIALOG_WIDTH = 700;
static constexpr const size_t DEFAULT_DIALOG_HEIGHT = 100;
static constexpr const unsigned int DEFAULT_WAIT_MS = 200;

MediaCopierDialogSlim::MediaCopierDialogSlim(QWidget *parent) :
    QDialog(parent), ui(new Ui::MediaCopierDialogSlim)
{
    ui->setupUi(this);
    this->resize(DEFAULT_DIALOG_WIDTH, DEFAULT_DIALOG_HEIGHT);
    this->setWindowTitle(mediacopier::MEDIACOPIER_PROJECT_NAME);
    move(screen()->geometry().center() - frameGeometry().center());
}

MediaCopierDialogSlim::~MediaCopierDialogSlim()
{
    delete ui;
}

void MediaCopierDialogSlim::init(std::shared_ptr<Config> config, QApplication& app)
{
    this->config = std::move(config);
    ui->param->init(this->config);

    fsm = std::make_unique<QStateMachine>();

    auto s1 = new QState();         // waiting for input
    auto s2 = new QState();         // executing operation
    auto s3 = new QFinalState();    // closing dialog

    s1->addTransition(ui->dialogButtonBox, &QDialogButtonBox::accepted, s2);
    s1->addTransition(ui->dialogButtonBox, &QDialogButtonBox::rejected, s3);
    s2->addTransition(this, &MediaCopierDialogSlim::operationDone, s3);

    QObject::connect(s2, &QState::entered, this, &MediaCopierDialogSlim::hide);
    QObject::connect(s2, &QState::entered, this, &MediaCopierDialogSlim::startOperation);
    QObject::connect(fsm.get(), &QStateMachine::finished, this, &MediaCopierDialogSlim::close);

    fsm->addState(s1);
    fsm->addState(s2);
    fsm->addState(s3);
    fsm->setInitialState(s1);
    fsm->start();
}

void MediaCopierDialogSlim::aboutToQuit()
{
    while (fsm->active())
        this->thread()->msleep(DEFAULT_WAIT_MS);
}

void MediaCopierDialogSlim::startOperation()
{
    worker = std::make_shared<Worker>(*config);

    QObject::connect(worker.get(), &Worker::finished, this, &MediaCopierDialogSlim::operationDone);

    worker->start();
}

void MediaCopierDialogSlim::cancelOperation()
{
    worker->kill();
}

void MediaCopierDialogSlim::awaitOperation()
{
    spdlog::default_logger()->flush();
}
