/* Copyright (C) 2022 Patrick Ziegler <zipat@proton.me>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "gui/MediaCopierParamWidget.hpp"
#include "config.hpp"

#include <QAbstractButton>
#include <QFileDialog>
#include <QCheckBox>

#include <spdlog/spdlog.h>

// auto generated by moc
#include "ui_MediaCopierParamWidget.h"

const auto ask_for_directory = [](const QString& title) -> QString
{
    return QFileDialog::getExistingDirectory(
                0, title, QDir::currentPath(),
                QFileDialog::ShowDirsOnly | QFileDialog::DontResolveSymlinks);
};

static const QList<Config::Command> commands = {
    Config::Command::COPY,
    Config::Command::MOVE
};

MediaCopierParamWidget::MediaCopierParamWidget(QWidget *parent) :
    QWidget(parent),
    ui(new Ui::MediaCopierParamWidget)
{
    ui->setupUi(this);

    Q_FOREACH(Config::Command item, commands) {
        ui->paramCommand->addItem(Config::commandString(item));
    }
    ui->paramPattern->setEnabled(false);
}

MediaCopierParamWidget::~MediaCopierParamWidget()
{
    delete ui;
}

void MediaCopierParamWidget::init(std::shared_ptr<Config> config)
{
    m_config = std::move(config);

    ui->dirsInputDirText->setText(QString::fromStdString(m_config->inputDir().string()));
    ui->dirsOutputDirText->setText(QString::fromStdString(m_config->outputDir().string()));
    ui->paramPattern->setText(m_config->pattern().c_str());
    for (int i = 0; i < commands.length(); ++i) {
        if (commands.at(i) == m_config->command()) {
            ui->paramCommand->setCurrentIndex(i);
            break;
        }
    }

    connect(ui->dirsInputDirButton, &QToolButton::clicked,
            this, &MediaCopierParamWidget::onOpenInputDirClicked);

    connect(ui->dirsOutputDirButton, &QToolButton::clicked,
            this, &MediaCopierParamWidget::onOpenOutputDirClicked);

    connect(ui->paramPatternUpdate, &QCheckBox::clicked,
            this, &MediaCopierParamWidget::onPatternUpdateClicked);

    connect(ui->dirsInputDirText, &QLineEdit::textChanged,
            this, &MediaCopierParamWidget::onInputDirChanged);

    connect(ui->dirsOutputDirText, &QLineEdit::textChanged,
            this, &MediaCopierParamWidget::onOutputDirChanged);

    connect(ui->paramPattern, &QLineEdit::textChanged,
            this, &MediaCopierParamWidget::onPatternChanged);

    connect(ui->paramCommand, QOverload<int>::of(&QComboBox::currentIndexChanged),
            this, &MediaCopierParamWidget::onCommandChanged);
}

void MediaCopierParamWidget::validateParameters()
{
    bool result = true;

    QPalette errorPalette;
    errorPalette.setColor(QPalette::Base, QColor(236, 116, 116));
    errorPalette.setColor(QPalette::Text, Qt::white);

    if (ui->dirsInputDirText->text().isEmpty() || !QDir(ui->dirsInputDirText->text()).exists()) {
        ui->dirsInputDirText->setPalette(errorPalette);
        result = false;
    } else {
        ui->dirsInputDirText->setPalette(this->style()->standardPalette());
    }

    if (ui->dirsOutputDirText->text().isEmpty() || !QDir(ui->dirsOutputDirText->text()).makeAbsolute()) {
        ui->dirsOutputDirText->setPalette(errorPalette);
        result = false;
    } else {
        ui->dirsOutputDirText->setPalette(this->style()->standardPalette());
    }

    if (ui->paramPattern->text().isEmpty()) {
        ui->paramPattern->setPalette(errorPalette);
        result = false;
    } else {
        ui->paramPattern->setPalette(this->style()->standardPalette());
    }

    if (result) {
        validParameters();
    } else {
        spdlog::error("Missing parameters, cannot start yet!");
        invalidParameters();
    }
}

void MediaCopierParamWidget::onOpenInputDirClicked()
{
    ui->dirsInputDirText->setText(ask_for_directory(QObject::tr("Source folder")));
}

void MediaCopierParamWidget::onOpenOutputDirClicked()
{
    ui->dirsOutputDirText->setText(ask_for_directory(QObject::tr("Destination folder")));
}

void MediaCopierParamWidget::onPatternUpdateClicked(bool checked)
{
    ui->paramPattern->setEnabled(checked);
    if (!checked) {
        m_config->resetPattern();
        m_config->readConfigFile();
        ui->paramPattern->setText(m_config->pattern().c_str());
    }
}

void MediaCopierParamWidget::onInputDirChanged(const QString& text)
{
    m_config->setInputDir(text);
    spdlog::debug("Changed input dir to " + m_config->outputDir().string());
}

void MediaCopierParamWidget::onOutputDirChanged(const QString& text)
{
    m_config->setOutputDir(text);
    spdlog::debug("Changed output dir to " + m_config->outputDir().string());
    if (!ui->paramPattern->isEnabled()) {
        m_config->resetPattern();
        if (QDir(text).exists()) {
            m_config->readConfigFile();
        }
    }
    ui->paramPattern->setText(m_config->pattern().c_str());
}

void MediaCopierParamWidget::onPatternChanged(const QString& text)
{
    m_config->setPattern(text);
    spdlog::debug("Changed pattern to " + m_config->pattern());
}

void MediaCopierParamWidget::onCommandChanged(int index)
{
    m_config->setCommand(commands.at(index));
    spdlog::debug("Changed command to " + Config::commandString(commands.at(index)).toStdString());
}
