set(CPACK_GENERATOR "RPM")
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CMAKE_INSTALL_PREFIX})

set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")

set(CPACK_PACKAGE_CONTACT "Patrick Ziegler")
set(CPACK_PACKAGE_VENDOR "Patrick Ziegler")

set(CPACK_RPM_PACKAGE_RELEASE 1)
set(CPACK_RPM_COMPONENT_INSTALL ON)

set(CPACK_RPM_APP_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_RPM_HEADERS_PACKAGE_NAME "${PROJECT_NAME}-devel")
set(CPACK_RPM_HEADERS_PACKAGE_REQUIRES "${PROJECT_NAME}")

set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CMAKE_PROJECT_VERSION}-${CPACK_RPM_PACKAGE_RELEASE}.${CMAKE_SYSTEM_PROCESSOR}")

include(CPack)
