name: build-and-test

on: ["push", "pull_request"]

jobs:
  build-and-test:
    strategy:
      matrix:
        config:
        - {name: "Ubuntu 20.04 (GCC)", os: "ubuntu-20.04", CC: "gcc", CXX: "g++"}
        - {name: "Ubuntu 20.04 (Clang)", os: "ubuntu-20.04", CC: "clang", CXX: "clang++"}

    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}

    steps:
    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: "noninteractive"
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake ffmpeg imagemagick libavformat-dev libexiv2-dev libimage-exiftool-perl libjpeg-dev libjpeg-progs liblog4cplus-dev qtbase5-dev

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create build directory
      run: mkdir -p ${{github.workspace}}/build

    - name: Configure build
      env:
        CC: ${{matrix.config.CC}}
        CXX: ${{matrix.config.CXX}}
      working-directory: ${{github.workspace}}/build
      run: cmake ..

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j$(nproc)

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: make test
