name: build-and-test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
    - name: Prepare build environment
      env:
        DEBIAN_FRONTEND: "noninteractive"
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake ffmpeg imagemagick libavformat-dev libexiv2-dev libimage-exiftool-perl libjpeg-dev libjpeg-progs liblog4cplus-dev qtbase5-dev

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create build directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ..

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j$(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: make test

